<?php
namespace Tests\Feature;
use App\Enums\ExperimentRunStatus; use App\Jobs\DispatchServerTracking; use App\Models\ExperimentRun; use App\Models\GroundTruthEvent; use App\Models\Product; use App\Models\ServerTrackingDispatch; use App\Services\ExperimentRunContext; use App\Tracking\Ga4ServerPayloadFactory; use App\Tracking\MetaServerPayloadFactory; use App\Tracking\ServerTrackingScheduler; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Http; use Illuminate\Support\Facades\Queue; use Tests\TestCase;
class ServerTrackingTest extends TestCase { use RefreshDatabase;
 private function configProviders():void{config()->set('tracking.ga4.server_enabled',true);config()->set('tracking.ga4.server_measurement_id','G-SERVER');config()->set('tracking.ga4.server_api_secret','secret');config()->set('tracking.meta.capi_enabled',true);config()->set('tracking.meta.pixel_id','123');config()->set('tracking.meta.capi_access_token','token');}
 private function event(string $mode='server_augmented',string $consent='full'):GroundTruthEvent{$run=ExperimentRun::create(['tracking_mode'=>$mode,'consent_mode'=>$consent]);$run->transitionTo(ExperimentRunStatus::Running);app(ExperimentRunContext::class)->bind($run);return app(\App\Services\GroundTruthRecorder::class)->viewItem(Product::factory()->create(['price_minor'=>1234]));}
 public function test_only_eligible_server_augmented_full_runs_schedule_dispatches():void{Queue::fake();$this->configProviders();$event=$this->event();app(ServerTrackingScheduler::class)->schedule($event);$this->assertSame(2,ServerTrackingDispatch::count());Queue::assertPushed(DispatchServerTracking::class,2);foreach([['client_only','full'],['server_augmented','partial'],['server_augmented','none']] as [$m,$c]){app(ServerTrackingScheduler::class)->schedule($this->event($m,$c));}$this->assertSame(2,ServerTrackingDispatch::count());}
 public function test_scheduler_is_idempotent_and_payloads_preserve_event_identity_and_time():void{Queue::fake();$this->configProviders();$event=$this->event();app(ServerTrackingScheduler::class)->schedule($event);app(ServerTrackingScheduler::class)->schedule($event);$this->assertSame(2,ServerTrackingDispatch::count());$ga=app(Ga4ServerPayloadFactory::class)->make($event);$this->assertSame($event->event_id,$ga['events'][0]['params']['testbed_event_id']);$this->assertSame('server',$ga['events'][0]['params']['tracking_channel']);$this->assertSame($event->occurred_at->timestamp*1000000,$ga['timestamp_micros']);$this->assertMatchesRegularExpression('/^\d+\.\d+$/',$ga['client_id']);$this->assertSame($ga['client_id'],app(Ga4ServerPayloadFactory::class)->clientId($event->experimentRun));$meta=app(MetaServerPayloadFactory::class)->make($event);$this->assertSame($event->event_id,$meta['data'][0]['event_id']);$this->assertSame($event->occurred_at->timestamp,$meta['data'][0]['event_time']);$this->assertSame('website',$meta['data'][0]['action_source']);$this->assertArrayNotHasKey('email',$meta['data'][0]['user_data']);}
 public function test_fake_successful_provider_responses_record_endpoint_acceptance_without_secrets():void{Queue::fake();$this->configProviders();$event=$this->event();app(ServerTrackingScheduler::class)->schedule($event);Http::fake(['*google-analytics.com*'=>Http::response('',204),'*graph.facebook.com*'=>Http::response(['events_received'=>1,'fbtrace_id'=>'trace'],200)]);foreach(ServerTrackingDispatch::all() as $d){app(DispatchServerTracking::class,['dispatchId'=>$d->id])->handle(app(Ga4ServerPayloadFactory::class),app(MetaServerPayloadFactory::class));}$this->assertSame(2,ServerTrackingDispatch::where('status','endpoint_accepted')->count());$this->assertSame(2,\App\Models\ServerTrackingAttempt::count());$this->assertStringNotContainsString('secret',json_encode(ServerTrackingDispatch::first()->request_payload));$this->assertStringNotContainsString('token',json_encode(ServerTrackingDispatch::where('provider','meta')->first()->request_payload));}
 public function test_completed_run_dispatch_remains_deliverable():void{Queue::fake();$this->configProviders();$event=$this->event();app(ServerTrackingScheduler::class)->schedule($event);$event->experimentRun->transitionTo(ExperimentRunStatus::Completed);Http::fake(['*'=>Http::response('',204)]);$d=ServerTrackingDispatch::where('provider','ga4')->first();app(DispatchServerTracking::class,['dispatchId'=>$d->id])->handle(app(Ga4ServerPayloadFactory::class),app(MetaServerPayloadFactory::class));$this->assertSame('endpoint_accepted',$d->fresh()->status->value);}
}
